apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: componenta-devfile-sample-go-basic-private-devfile-nested-kszb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-olcz-tenant/mc-golang-nested/componenta-devfile-sample-go-basic-private-devfile-nested-kszb@sha256:58c0d497b5840d9acf52017f788a488268f824a047c3059894676063013a80f5
        name: my-go
        resources: {}
status: {}
