apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: componentb-devfile-sample-go-basic-private-devfile-nested-tfk5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: componentb-devfile-sample-go-basic-private-devfile-nested-tfk5
    app.kubernetes.io/part-of: mc-golang-nested
  name: componentb-devfile-sample-go-basic-private-devfile-nested-tfk5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: componentb-devfile-sample-go-basic-private-devfile-nested-tfk5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: componentb-devfile-sample-go-basic-private-devfile-nested-tfk5
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-olcz-tenant/mc-golang-nested/componentb-devfile-sample-go-basic-private-devfile-nested-tfk5@sha256:76b18b97e56236a642d4171f4c54d0d68e1f30b508f78f9641fdabd7682243bf
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
